import React from "react";
import {AbsoluteFill} from "remotion";
import {displayFont, fontCss, monoFont, sansFont} from "./fonts";

const C = {ink: "#101311", paper: "#f2efe8", orange: "#ff6038", green: "#a5e3c5", white: "#ffffff"};

const Mark = () => <svg width="62" height="62" viewBox="0 0 54 54"><circle cx="27" cy="27" r="5.5" fill={C.orange}/><path d="M27 27V5M27 27L7 40M27 27L47 40" stroke={C.orange} strokeWidth="7.5" strokeLinecap="round"/></svg>;

export const PrizePicksThumbnail: React.FC = () => <AbsoluteFill style={{background: C.ink, color: C.white, overflow: "hidden", fontFamily: displayFont}}><style>{fontCss}</style><div style={{position: "absolute", inset: 0, backgroundImage: "linear-gradient(rgba(242,239,232,.05) 1px,transparent 1px),linear-gradient(90deg,rgba(242,239,232,.05) 1px,transparent 1px)", backgroundSize: "34px 34px"}}/><div style={{position: "absolute", left: 0, top: 0, width: 22, height: "100%", background: C.orange}}/><div style={{position: "relative", height: "100%", padding: "56px 64px", display: "grid", gridTemplateColumns: "1.16fr .84fr", gap: 36}}><div style={{display: "flex", flexDirection: "column", justifyContent: "space-between"}}><div style={{display: "flex", alignItems: "center", gap: 14}}><Mark/><div style={{fontSize: 27, fontWeight: 700}}>PROPELLER <span style={{color: C.orange}}>PICKS</span></div></div><div><div style={{fontSize: 122, fontWeight: 700, lineHeight: .76, letterSpacing: -4}}>POWER<br/><span style={{color: C.orange}}>vs.</span> FLEX</div><div style={{fontFamily: monoFont, fontSize: 24, letterSpacing: 2.2, color: C.paper, marginTop: 30}}>PICKS · PAYOUTS · RULES</div></div><div style={{fontFamily: sansFont, fontSize: 20, color: "#b8c0ba"}}>CURRENT OFFICIAL RATES · DETAILS SCREEN CONTROLS</div></div><div style={{display: "grid", gridTemplateRows: "1fr 1fr", gap: 18, padding: "12px 0"}}><div style={{borderRadius: 22, background: C.orange, color: C.ink, padding: "29px 32px", display: "flex", alignItems: "center", justifyContent: "space-between", rotate: "-2deg"}}><div><div style={{fontFamily: monoFont, fontSize: 17}}>POWER</div><div style={{fontSize: 57, fontWeight: 700, marginTop: 8}}>ALL CORRECT</div></div><div style={{fontSize: 76, fontWeight: 700}}>✓✓✓✓</div></div><div style={{borderRadius: 22, background: C.paper, color: C.ink, padding: "29px 32px", display: "flex", alignItems: "center", justifyContent: "space-between", rotate: "2deg"}}><div><div style={{fontFamily: monoFont, fontSize: 17}}>FLEX</div><div style={{fontSize: 57, fontWeight: 700, marginTop: 8}}>PAYOUT TIERS</div></div><div style={{fontSize: 76, fontWeight: 700, color: "#147d50"}}>✓✓✓×</div></div></div></div></AbsoluteFill>;
