import {Audio} from "@remotion/media";
import React from "react";
import {AbsoluteFill, Easing, Img, interpolate, Sequence, staticFile, useCurrentFrame} from "remotion";
import {Captions} from "./Captions";
import {DURATION_FRAMES, flexRates, FPS, powerRates, scenes, type Scene} from "./data";
import {displayFont, fontCss, monoFont, sansFont} from "./fonts";

const C = {ink: "#101311", ink2: "#1c211e", paper: "#f2efe8", white: "#fff", orange: "#ff6038", green: "#147d50", mint: "#a5e3c5", muted: "#aab3ad", line: "#343b36", red: "#e34535"};
const clamp = {extrapolateLeft: "clamp" as const, extrapolateRight: "clamp" as const};

const Mark: React.FC<{size?: number}> = ({size = 43}) => <svg width={size} height={size} viewBox="0 0 54 54"><circle cx="27" cy="27" r="5.5" fill={C.orange}/><path d="M27 27V5M27 27L7 40M27 27L47 40" stroke={C.orange} strokeWidth="7.5" strokeLinecap="round"/></svg>;

const Tag: React.FC<{children: React.ReactNode; tone?: "orange" | "green" | "paper" | "dark"}> = ({children, tone = "dark"}) => {
  const pair = {orange: [C.orange, C.ink], green: [C.mint, C.ink], paper: [C.paper, C.ink], dark: [C.ink2, C.white]}[tone];
  return <span style={{display: "inline-flex", padding: "8px 14px", borderRadius: 999, background: pair[0], color: pair[1], fontFamily: monoFont, fontSize: 13, letterSpacing: 1.1, border: `1px solid ${tone === "dark" ? C.line : pair[0]}`}}>{children}</span>;
};

const Dots: React.FC<{count: number; partial?: boolean}> = ({count, partial}) => {
  const frame = useCurrentFrame();
  return <div style={{display: "flex", gap: 15}}>{Array.from({length: count}, (_, index) => <div key={index} style={{width: 60, height: 60, borderRadius: 17, display: "grid", placeItems: "center", background: partial && index === count - 1 ? "#2a302c" : C.orange, border: `2px solid ${partial && index === count - 1 ? "#68716b" : C.orange}`, color: C.white, fontFamily: displayFont, fontSize: 34, fontWeight: 700, opacity: interpolate(frame, [index * 6, index * 6 + 9], [0, 1], clamp), translate: `0 ${interpolate(frame, [index * 6, index * 6 + 9], [18, 0], clamp)}px`}}>{partial && index === count - 1 ? "×" : "✓"}</div>)}</div>;
};

const SceneShell: React.FC<{scene: Scene; children: React.ReactNode}> = ({scene, children}) => {
  const frame = useCurrentFrame();
  return <AbsoluteFill style={{overflow: "hidden", color: C.white, background: C.ink, backgroundImage: "linear-gradient(rgba(242,239,232,.045) 1px,transparent 1px),linear-gradient(90deg,rgba(242,239,232,.045) 1px,transparent 1px),radial-gradient(circle at 82% 6%,rgba(255,96,56,.18),transparent 32%)", backgroundSize: "42px 42px,42px 42px,100% 100%"}}><div style={{height: "100%", padding: "28px 62px 118px", display: "flex", flexDirection: "column", gap: 13}}><div style={{height: 58, display: "flex", alignItems: "center", justifyContent: "space-between"}}><div style={{display: "flex", alignItems: "center", gap: 12}}><Mark/><div><div style={{fontFamily: displayFont, fontSize: 24, fontWeight: 700, lineHeight: .85}}>PROPELLER</div><div style={{fontFamily: monoFont, fontSize: 10, letterSpacing: 5, color: C.orange, marginTop: 7}}>PICKS</div></div></div><div style={{display: "flex", gap: 10}}><Tag>{scene.id} / 10</Tag><Tag tone="orange">OFFICIAL RULES CHECKED · AUG 16, 2026</Tag></div></div><div style={{opacity: interpolate(frame, [0, 10], [0, 1], clamp), translate: `0 ${interpolate(frame, [0, 13], [18, 0], {...clamp, easing: Easing.out(Easing.cubic)})}px`}}><div style={{fontFamily: monoFont, fontSize: 14, letterSpacing: 2.3, color: C.orange}}>{scene.eyebrow}</div><div style={{fontFamily: displayFont, fontSize: 53, fontWeight: 700, letterSpacing: -1.4, lineHeight: .96, marginTop: 6}}>{scene.title}</div></div><div style={{flex: 1, minHeight: 0}}>{children}</div></div></AbsoluteFill>;
};

const Intro = () => <div style={{height: "100%", display: "grid", gridTemplateColumns: "1fr 1fr", gap: 28, alignItems: "center"}}>{[
  {label: "POWER PLAY", headline: <>ALL ACTIVE<br/>PICKS CORRECT</>, copy: "The listed standard payout sits on the sweep.", bg: C.orange, fg: C.ink, partial: false},
  {label: "FLEX PLAY", headline: <>PARTIAL-RESULT<br/>PAYOUT TIERS</>, copy: "Lower top multiplier at the same count; more than one payout outcome.", bg: C.paper, fg: C.ink, partial: true},
].map((item) => <div key={item.label} style={{height: 620, borderRadius: 24, background: item.bg, color: item.fg, padding: "44px 42px", display: "flex", flexDirection: "column", justifyContent: "space-between", boxShadow: "16px 18px 0 rgba(255,96,56,.14)"}}><Tag tone={item.partial ? "green" : "paper"}>{item.label}</Tag><div><div style={{fontFamily: displayFont, fontSize: 83, fontWeight: 700, lineHeight: .87}}>{item.headline}</div><div style={{fontFamily: sansFont, fontSize: 22, lineHeight: 1.35, marginTop: 22}}>{item.copy}</div></div><Dots count={4} partial={item.partial}/></div>)}</div>;

const Rules = () => <div style={{height: "100%", display: "grid", gridTemplateColumns: ".76fr 1.24fr", gap: 34, alignItems: "center"}}><div style={{height: 610, borderRadius: 24, background: C.paper, color: C.ink, padding: "39px 40px", display: "flex", flexDirection: "column", justifyContent: "space-between"}}><Tag tone="orange">PLAYER PICKS</Tag><div><div style={{fontFamily: displayFont, fontSize: 144, fontWeight: 700, lineHeight: .8}}>2–6<span style={{color: C.orange}}>*</span></div><div style={{fontFamily: displayFont, fontSize: 48, fontWeight: 700, marginTop: 20}}>PROJECTIONS</div></div><div style={{fontFamily: sansFont, fontSize: 20, lineHeight: 1.45, color: "#4f5651"}}><b style={{color: C.orange}}>*</b> Colorado currently requires at least three. Other eligibility rules vary by location.</div></div><div style={{display: "grid", gap: 14}}>{[
  ["01", "AT LEAST TWO TEAMS", "A standard Player Pick lineup cannot contain athletes from only one team."],
  ["02", "REGION CONTROLS ACCESS", "Age, eligible pick types, sports, and periods can differ by jurisdiction."],
  ["03", "SPORT-SPECIFIC SCORING", "The in-app scoring chart can add league-level restrictions and activity thresholds."],
].map(([n, h, d], index) => <div key={n} style={{background: C.ink2, border: `1px solid ${C.line}`, borderLeft: `8px solid ${index === 1 ? C.mint : C.orange}`, borderRadius: 16, padding: "22px 25px", display: "grid", gridTemplateColumns: "75px 1fr", gap: 17}}><div style={{fontFamily: monoFont, fontSize: 17, color: index === 1 ? C.mint : C.orange}}>{n}</div><div><div style={{fontFamily: displayFont, fontSize: 30, fontWeight: 700}}>{h}</div><div style={{fontFamily: sansFont, fontSize: 17, lineHeight: 1.4, color: C.muted, marginTop: 5}}>{d}</div></div></div>)}</div></div>;

const PowerChart = () => {
  const frame = useCurrentFrame();
  return <div style={{height: "100%", display: "grid", gridTemplateColumns: ".52fr 1.48fr", gap: 32, alignItems: "center"}}><div><div style={{fontFamily: displayFont, fontSize: 96, lineHeight: .88, fontWeight: 700}}>ONE<br/><span style={{color: C.orange}}>WINNING</span><br/>TIER</div><div style={{fontFamily: sansFont, fontSize: 21, color: C.muted, lineHeight: 1.45, marginTop: 24}}>All active picks must be correct for the listed standard Power payout.</div></div><div style={{display: "grid", gridTemplateColumns: "repeat(5,1fr)", gap: 14, height: 560, alignItems: "end"}}>{powerRates.map((rate, index) => <div key={rate.picks} style={{height: 205 + index * 76, borderRadius: "18px 18px 8px 8px", background: index === 2 ? C.orange : C.ink2, color: index === 2 ? C.ink : C.white, border: `1px solid ${index === 2 ? C.orange : C.line}`, padding: "24px 18px", display: "flex", flexDirection: "column", justifyContent: "space-between", opacity: interpolate(frame, [index * 8, index * 8 + 12], [0, 1], clamp), translate: `0 ${interpolate(frame, [index * 8, index * 8 + 12], [40, 0], clamp)}px`}}><div><div style={{fontFamily: monoFont, fontSize: 13}}>{rate.picks} PICKS</div><div style={{fontFamily: displayFont, fontSize: 57, fontWeight: 700, marginTop: 8}}>{rate.multiplier}</div></div><div style={{fontFamily: monoFont, fontSize: 14}}>{rate.result} CORRECT</div></div>)}</div></div>;
};

const FlexChart = () => {
  const frame = useCurrentFrame();
  return <div style={{height: "100%", display: "flex", flexDirection: "column", justifyContent: "center", gap: 17}}><div style={{display: "grid", gridTemplateColumns: "repeat(5,1fr)", gap: 14}}>{flexRates.map((rate, index) => <div key={rate.picks} style={{minHeight: 425, borderRadius: 18, background: rate.picks === "4" ? C.paper : C.ink2, color: rate.picks === "4" ? C.ink : C.white, border: `1px solid ${rate.picks === "4" ? C.paper : C.line}`, padding: "24px 21px", opacity: interpolate(frame, [index * 7, index * 7 + 11], [0, 1], clamp), translate: `0 ${interpolate(frame, [index * 7, index * 7 + 11], [26, 0], clamp)}px`}}><div style={{display: "flex", justifyContent: "space-between", alignItems: "center"}}><div style={{fontFamily: displayFont, fontSize: 58, fontWeight: 700}}>{rate.picks}</div><Tag tone={rate.picks === "4" ? "orange" : "dark"}>PICKS</Tag></div><div style={{height: 1, background: rate.picks === "4" ? "#d3cdc1" : C.line, margin: "19px 0"}}/>{rate.tiers.map((tier, tierIndex) => <div key={tier} style={{borderRadius: 11, padding: "15px 14px", marginTop: 11, background: tierIndex === 0 ? (rate.picks === "4" ? C.orange : "#252b27") : (rate.picks === "4" ? "#e2ddd3" : "#141815"), fontFamily: monoFont, fontSize: 17, color: rate.picks === "4" ? C.ink : (tierIndex === 0 ? "#ffb29e" : C.muted)}}>{tier}</div>)}</div>)}</div><div style={{display: "flex", justifyContent: "space-between"}}><div style={{display: "flex", gap: 10}}><Tag tone="green">LIVE OFFICIAL TABLES AGREE: 4-PICK FLEX = 6x</Tag><Tag>SEARCH SNAPSHOT WAS STALE</Tag></div><Tag tone="orange">DETAILS SCREEN CONTROLS</Tag></div></div>;
};

const Capture: React.FC<{type: "power" | "flex"; mobile?: boolean; top?: boolean}> = ({type, mobile, top}) => {
  const frame = useCurrentFrame();
  const y = mobile ? (top ? 0 : type === "power" ? -650 : -590) : 0;
  return <Img src={staticFile(`assets/captures/${mobile ? "mobile" : "desktop"}/calculator-${type}-4-pick-20.png`)} style={{width: "100%", height: mobile ? "auto" : "100%", objectFit: mobile ? undefined : "cover", objectPosition: top ? "center top" : "center bottom", translate: mobile ? `0 ${y + interpolate(frame, [0, 220], [0, -18], clamp)}px` : "0 0", scale: mobile ? 1 : interpolate(frame, [0, 240], [1, 1.025], clamp)}}/>;
};

const ProductPair: React.FC<{type: "power" | "flex"; top?: boolean}> = ({type, top}) => <div style={{height: "100%", display: "grid", gridTemplateColumns: "1fr 300px", gap: 30, alignItems: "center"}}><div style={{height: 605, borderRadius: 21, background: "#090b0a", padding: "48px 9px 9px", position: "relative", overflow: "hidden", border: `1px solid ${C.line}`, boxShadow: "14px 16px 0 rgba(255,96,56,.14)"}}><div style={{position: "absolute", top: 18, left: 18, display: "flex", gap: 8}}>{[C.red,"#f0bc45",C.green].map(color => <i key={color} style={{width: 11, height: 11, borderRadius: 99, background: color}}/>)}</div><div style={{position: "absolute", top: 10, left: 111, right: 15, height: 29, borderRadius: 7, background: C.ink2, color: C.muted, fontFamily: monoFont, fontSize: 11, padding: "7px 12px"}}>propellerpicks.com/tools/prizepicks-payout-calculator/ · {type.toUpperCase()} · 4 PICKS · $20</div><div style={{height: "100%", borderRadius: 12, overflow: "hidden", background: C.white}}><Capture type={type} top={top}/></div></div><div style={{height: 610, width: 300, borderRadius: 47, background: "#080a09", border: "4px solid #39403b", padding: 11, position: "relative", boxShadow: "12px 14px 0 rgba(165,227,197,.12)"}}><div style={{position: "absolute", zIndex: 3, top: 17, left: "50%", translate: "-50% 0", width: 79, height: 17, borderRadius: 20, background: "#080a09"}}/><div style={{height: "100%", borderRadius: 34, overflow: "hidden", background: C.white}}><Capture type={type} mobile top={top}/></div></div></div>;

const Example = () => {const frame = useCurrentFrame(); const type = frame < 430 ? "power" : "flex"; return <div style={{height: "100%", position: "relative"}}><ProductPair type={type}/><div style={{position: "absolute", left: 38, top: 36}}><Tag tone={type === "power" ? "orange" : "green"}>{type === "power" ? "4 / 4 → $200 TOTAL PAYOUT · 10x" : "4 / 4 → $120 · 6x   |   3 / 4 → $30 · 1.5x"}</Tag></div><div style={{position: "absolute", left: 38, bottom: 26}}><Tag>STANDARD-RATE SCENARIO · TOTAL PAYOUT, NOT PROFIT</Tag></div></div>};

const Details = () => <div style={{height: "100%", display: "grid", gridTemplateColumns: ".82fr 1.18fr", gap: 32, alignItems: "center"}}><div style={{display: "grid", gap: 13}}>{["PROJECTION TYPE", "PROMOTION", "PICK COMBINATION", "PLAYER + TEAM PICKS", "FEE ALLOCATION", "OTHER DISCLOSED FACTORS"].map((item, index) => <div key={item} style={{borderRadius: 11, padding: "14px 18px", background: C.ink2, border: `1px solid ${C.line}`, fontFamily: monoFont, fontSize: 16, color: index === 0 ? C.orange : C.muted}}>{String(index + 1).padStart(2, "0")} · {item}</div>)}</div><div style={{height: 600, borderRadius: 24, background: C.paper, color: C.ink, padding: "38px 42px", display: "flex", flexDirection: "column", justifyContent: "space-between", boxShadow: "17px 19px 0 rgba(255,96,56,.18)"}}><div style={{display: "flex", justifyContent: "space-between"}}><Tag tone="orange">EDITORIAL REPRESENTATION</Tag><Tag tone="paper">NOT AN APP CAPTURE</Tag></div><div><div style={{fontFamily: monoFont, fontSize: 14, color: "#69716c"}}>INDIVIDUAL LINEUP DETAILS</div><div style={{fontFamily: displayFont, fontSize: 108, fontWeight: 700, lineHeight: .82, marginTop: 18}}>DISPLAYED<br/><span style={{color: C.orange}}>PAYOUT</span></div></div><div style={{borderRadius: 15, padding: "22px 24px", background: C.ink, color: C.white}}><div style={{fontFamily: monoFont, fontSize: 12, color: C.muted}}>CURRENT NUMBER</div><div style={{fontFamily: displayFont, fontSize: 30, fontWeight: 700, marginTop: 5}}>CONTROLS OVER GENERAL CHARTS</div></div></div></div>;

const Reversions = () => <div style={{height: "100%", display: "grid", gridTemplateColumns: "1fr .3fr 1fr", gap: 26, alignItems: "center"}}>{[
  {tag: "BEFORE", count: 4, label: "4–PICK", bg: C.ink2, fg: C.white},
  {tag: "REVERTED", count: 3, label: "3–PICK", bg: C.paper, fg: C.ink},
].map((item, index) => <React.Fragment key={item.tag}>{index === 1 ? <div style={{display: "grid", placeItems: "center"}}><div style={{width: 130, height: 130, borderRadius: 999, background: C.orange, color: C.ink, display: "grid", placeItems: "center", fontFamily: displayFont, fontSize: 65, fontWeight: 700}}>→</div></div> : null}<div style={{height: 480, borderRadius: 21, background: item.bg, color: item.fg, border: `1px solid ${C.line}`, padding: 34, display: "flex", flexDirection: "column", justifyContent: "space-between", gridColumn: index === 0 ? 1 : 3}}><Tag tone={index ? "orange" : "dark"}>{item.tag}</Tag><div style={{fontFamily: displayFont, fontSize: 112, fontWeight: 700}}>{item.label}</div><Dots count={item.count}/><div style={{fontFamily: monoFont, fontSize: 14}}>2-PICK REVERSION → NORMALLY REFUND</div></div></React.Fragment>) }<div style={{position: "absolute", left: 62, right: 62, bottom: 122, display: "grid", gridTemplateColumns: "repeat(3,1fr)", gap: 12}}>{[["DNP","Projection removed"],["ELIGIBLE REBOOT","Sport-specific"],["TIE","Tier lowers; pick remains"]].map(([a,b], index) => <div key={a} style={{background: index === 1 ? C.mint : index === 2 ? C.paper : C.orange, color: C.ink, borderRadius: 11, padding: "12px 16px", display: "flex", justifyContent: "space-between", fontFamily: monoFont, fontSize: 13}}><span>{a}</span><span>{b}</span></div>)}</div></div>;

const Calculator = () => {const frame = useCurrentFrame(); const type = frame < 390 ? "power" : "flex"; return <div style={{height: "100%", position: "relative"}}><ProductPair type={type} top/><div style={{position: "absolute", right: 360, bottom: 32, width: 720, background: "rgba(16,19,17,.96)", border: `1px solid ${C.line}`, borderRadius: 15, padding: "19px 23px", boxShadow: `9px 10px 0 ${C.orange}`}}><div style={{fontFamily: monoFont, fontSize: 14, color: C.orange}}>VISITOR-SUPPLIED HIT RATE</div><div style={{fontFamily: displayFont, fontSize: 34, fontWeight: 700, marginTop: 7}}>SCENARIO INPUT ≠ PROPELLER PREDICTION</div></div><div style={{position: "absolute", left: 35, top: 35}}><Tag tone="green">FRESH LOCAL UI · DESKTOP + MOBILE · AUG 16</Tag></div></div>};

const Summary = () => <div style={{height: "100%", display: "grid", gridTemplateColumns: "1fr 1fr", gap: 28, alignItems: "center"}}>{[
  ["POWER", "ALL\nACTIVE\nPICKS", "Higher standard sweep multiplier at the same count.", C.orange],
  ["FLEX", "MORE\nPAYOUT\nTIERS", "A different outcome distribution—not proof that an entry is good.", C.paper],
].map(([tag, title, copy, bg]) => <div key={tag} style={{height: 540, borderRadius: 24, background: bg, color: C.ink, padding: 42, display: "flex", flexDirection: "column", justifyContent: "space-between"}}><Tag tone={tag === "POWER" ? "paper" : "green"}>{tag}</Tag><div style={{fontFamily: displayFont, fontSize: 103, fontWeight: 700, lineHeight: .82, whiteSpace: "pre-line"}}>{title}</div><div style={{fontFamily: sansFont, fontSize: 22}}>{copy}</div></div>)}</div>;

const CTA = () => <div style={{height: "100%", display: "grid", gridTemplateColumns: ".78fr 1.22fr", gap: 38, alignItems: "center"}}><div><Mark size={72}/><div style={{fontFamily: displayFont, fontSize: 80, fontWeight: 700, lineHeight: .86, marginTop: 25}}>RESEARCH<br/>THE RULE.<br/><span style={{color: C.orange}}>VERIFY</span><br/>THE SCREEN.</div><div style={{marginTop: 28}}><Tag tone="orange">PROPELLERPICKS.COM/TOOLS/PRIZEPICKS-PAYOUT-CALCULATOR/</Tag></div></div><div style={{height: 615, borderRadius: 24, background: C.paper, color: C.ink, padding: "40px 42px", display: "flex", flexDirection: "column", justifyContent: "space-between"}}><div><Tag tone="green">PRIMARY SOURCES</Tag><div style={{display: "grid", gap: 12, marginTop: 25}}>{["PAYOUTS · UPDATED AUG 11", "PLAYER PICKS · UPDATED JUL 16", "DNPs / REBOOTS / TIES · UPDATED AUG 11", "ELIGIBILITY · UPDATED AUG 14"].map((source, index) => <div key={source} style={{display: "grid", gridTemplateColumns: "54px 1fr", gap: 15, padding: "15px 17px", borderRadius: 11, background: index === 0 ? C.orange : "#dfdbd1", fontFamily: monoFont, fontSize: 14}}><span>{String(index + 1).padStart(2, "0")}</span><span>{source}</span></div>)}</div></div><div><div style={{fontFamily: sansFont, fontSize: 19, lineHeight: 1.45}}>Independent research only. Not affiliated with PrizePicks. No wager placement. No promised outcomes.</div><div style={{fontFamily: monoFont, fontSize: 14, color: "#59605c", marginTop: 13}}>AGE AND AVAILABILITY VARY · 1-800-GAMBLER</div></div></div></div>;

const SceneBody: React.FC<{scene: Scene}> = ({scene}) => {
  const body = scene.kind === "intro" ? <Intro/> : scene.kind === "rules" ? <Rules/> : scene.kind === "power-chart" ? <PowerChart/> : scene.kind === "flex-chart" ? <FlexChart/> : scene.kind === "example" ? <Example/> : scene.kind === "details" ? <Details/> : scene.kind === "reversions" ? <Reversions/> : scene.kind === "calculator" ? <Calculator/> : scene.kind === "summary" ? <Summary/> : <CTA/>;
  return <SceneShell scene={scene}>{body}</SceneShell>;
};

export const PrizePicksPowerFlexVideo: React.FC<{showCaptions: boolean}> = ({showCaptions}) => <AbsoluteFill style={{background: C.ink}}><style>{fontCss}</style><Audio src={staticFile("assets/narration.mp3")}/>{scenes.map((scene) => <Sequence key={scene.id} from={Math.round(scene.start * FPS)} durationInFrames={Math.max(1, Math.round((scene.end - scene.start) * FPS))}><SceneBody scene={scene}/></Sequence>)}{showCaptions ? <Captions/> : null}<Sequence from={DURATION_FRAMES - 1}><AbsoluteFill style={{background: C.ink}}/></Sequence></AbsoluteFill>;
