export type Crop = {
  x: number;
  y: number;
  width: number;
  height: number;
};

export type WalkthroughScene = {
  start: number;
  end: number;
  eyebrow: string;
  title: string;
  platform: string;
  layout: "desktop" | "mobile" | "dual" | "statement";
  asset?: string;
  sourceWidth?: number;
  sourceHeight?: number;
  crop?: Crop;
  cropTo?: Crop;
  zoom?: number;
  focusX?: number;
  mobileAsset?: string;
  mobileSourceWidth?: number;
  mobileSourceHeight?: number;
  mobileCrop?: Crop;
  mobileZoom?: number;
  callout: string;
  points?: string[];
  accent?: "orange" | "green";
};

export const scenes: WalkthroughScene[] = [
  {
    start: 0,
    end: 17.7,
    eyebrow: "Confidence score walkthrough",
    title: "What does 72 confidence actually mean?",
    platform: "Desktop + mobile",
    layout: "dual",
    asset: "desktop-detail.png",
    sourceWidth: 1920,
    sourceHeight: 1080,
    crop: {x: 380, y: 110, width: 1335, height: 720},
    mobileAsset: "mobile-detail.png",
    mobileSourceWidth: 1320,
    mobileSourceHeight: 2868,
    mobileCrop: {x: 0, y: 160, width: 1320, height: 1700},
    callout: "Confidence is a research signal—not a win probability.",
  },
  {
    start: 17.7,
    end: 35.18,
    eyebrow: "One historical example",
    title: "The same prop on both platforms",
    platform: "79 confidence · LESS 0.5 RBIs",
    layout: "dual",
    asset: "desktop-detail.png",
    sourceWidth: 1920,
    sourceHeight: 1080,
    crop: {x: 390, y: 125, width: 1320, height: 700},
    mobileAsset: "mobile-detail.png",
    mobileSourceWidth: 1320,
    mobileSourceHeight: 2868,
    mobileCrop: {x: 0, y: 190, width: 1320, height: 1500},
    callout: "Different number. Same way of reading the score.",
    accent: "green",
  },
  {
    start: 35.18,
    end: 50.26,
    eyebrow: "Step 1 · Scan",
    title: "Start on the Props Board",
    platform: "Desktop",
    layout: "desktop",
    asset: "desktop-board.png",
    sourceWidth: 1920,
    sourceHeight: 1080,
    crop: {x: 205, y: 70, width: 1530, height: 890},
    callout: "Everything stays attached",
    points: ["Player + market", "Direction + exact line", "Source + confidence"],
  },
  {
    start: 50.26,
    end: 68.36,
    eyebrow: "Step 2 · Open",
    title: "Move from the board to Prop Detail",
    platform: "Desktop",
    layout: "desktop",
    asset: "desktop-detail.png",
    sourceWidth: 1920,
    sourceHeight: 1080,
    crop: {x: 390, y: 100, width: 1320, height: 810},
    callout: "The full research workspace",
    points: ["Recommendation", "Recent results", "Market + evidence"],
    accent: "green",
  },
  {
    start: 68.36,
    end: 83.46,
    eyebrow: "Direction + line",
    title: "Desktop repeats the line in three places",
    platform: "Desktop",
    layout: "desktop",
    asset: "desktop-detail.png",
    sourceWidth: 1920,
    sourceHeight: 1080,
    crop: {x: 410, y: 125, width: 1305, height: 635},
    cropTo: {x: 900, y: 125, width: 815, height: 635},
    zoom: 1.16,
    callout: "LESS and 0.5 define the question",
    points: ["Top recommendation", "Summary card", "Market panel"],
  },
  {
    start: 83.46,
    end: 103.14,
    eyebrow: "Direction + line",
    title: "Mobile puts the line beside the stat",
    platform: "Mobile companion",
    layout: "mobile",
    asset: "mobile-detail.png",
    sourceWidth: 1320,
    sourceHeight: 2868,
    crop: {x: 0, y: 210, width: 1320, height: 1500},
    zoom: 1.14,
    callout: "Line Check repeats 0.5 and compares the market average.",
    points: ["LESS 0.5", "This line 0.5", "Market average 0.5"],
    accent: "green",
  },
  {
    start: 103.14,
    end: 111.26,
    eyebrow: "Confidence",
    title: "Desktop gives confidence its own summary card",
    platform: "Desktop",
    layout: "desktop",
    asset: "desktop-detail.png",
    sourceWidth: 1920,
    sourceHeight: 1080,
    crop: {x: 760, y: 295, width: 530, height: 420},
    zoom: 1.18,
    callout: "79 = model conviction",
    accent: "green",
  },
  {
    start: 111.26,
    end: 130.9,
    eyebrow: "Confidence",
    title: "Mobile keeps the same score easy to find",
    platform: "Mobile companion",
    layout: "mobile",
    asset: "mobile-detail.png",
    sourceWidth: 1320,
    sourceHeight: 2868,
    crop: {x: 0, y: 180, width: 1320, height: 1840},
    cropTo: {x: 0, y: 350, width: 1320, height: 1840},
    zoom: 1.16,
    callout: "Confidence ring → Model Read",
    points: ["Historical example: 79", "A score of 72 reads the same way", "Not a guarantee"],
  },
  {
    start: 130.9,
    end: 147.34,
    eyebrow: "Two measurements",
    title: "Confidence is not chance to hit",
    platform: "Mobile Model Read",
    layout: "mobile",
    asset: "mobile-detail.png",
    sourceWidth: 1320,
    sourceHeight: 2868,
    crop: {x: 0, y: 1530, width: 1320, height: 1300},
    zoom: 1.16,
    callout: "79% confidence and 59% chance to hit are separate.",
    accent: "green",
  },
  {
    start: 147.34,
    end: 163.74,
    eyebrow: "Evidence",
    title: "Read Why This Lean before deciding",
    platform: "Desktop",
    layout: "desktop",
    asset: "desktop-why.png",
    sourceWidth: 1920,
    sourceHeight: 1080,
    crop: {x: 390, y: 165, width: 1320, height: 775},
    zoom: 1.14,
    callout: "Model output becomes readable reasons",
    points: ["Usage", "Matchup", "Role + results against the line"],
  },
  {
    start: 163.74,
    end: 193.44,
    eyebrow: "Agent breakdown",
    title: "See which agents support the direction",
    platform: "Desktop",
    layout: "desktop",
    asset: "desktop-agents.png",
    sourceWidth: 1920,
    sourceHeight: 1080,
    crop: {x: 390, y: 500, width: 930, height: 510},
    cropTo: {x: 420, y: 555, width: 900, height: 455},
    zoom: 1.13,
    focusX: 0.42,
    callout: "Independent contributors",
    points: ["Market + hit rate", "Injury + matchup", "Ballpark + usage + lineup"],
  },
  {
    start: 193.44,
    end: 208.38,
    eyebrow: "Mobile Model Read",
    title: "Drivers, agreement, signal mix—then agents",
    platform: "iOS companion",
    layout: "mobile",
    asset: "ipad-model.png",
    sourceWidth: 2064,
    sourceHeight: 2752,
    crop: {x: 20, y: 900, width: 2020, height: 1850},
    zoom: 1.14,
    callout: "Continue down to Agent Breakdown",
    points: ["Top driver", "Signal mix", "Individual agents"],
  },
  {
    start: 208.38,
    end: 231.7,
    eyebrow: "Confidence in context",
    title: "Stronger evidence still leaves uncertainty",
    platform: "Research workflow",
    layout: "desktop",
    asset: "desktop-detail.png",
    sourceWidth: 1920,
    sourceHeight: 1080,
    crop: {x: 390, y: 120, width: 1320, height: 820},
    callout: "The score begins research—it does not end it.",
    points: ["Lineups change", "Markets move", "Variance remains"],
  },
  {
    start: 231.7,
    end: 238.5,
    eyebrow: "New-user workflow · 1",
    title: "Scan the board and open a prop",
    platform: "Desktop",
    layout: "desktop",
    asset: "desktop-board.png",
    sourceWidth: 1920,
    sourceHeight: 1080,
    crop: {x: 205, y: 70, width: 1530, height: 890},
    callout: "Start broad. Then investigate.",
  },
  {
    start: 238.5,
    end: 245.86,
    eyebrow: "New-user workflow · 2",
    title: "Confirm direction and exact line",
    platform: "Mobile companion",
    layout: "mobile",
    asset: "mobile-detail.png",
    sourceWidth: 1320,
    sourceHeight: 2868,
    crop: {x: 0, y: 210, width: 1320, height: 1450},
    callout: "LESS 0.5 RBIs",
    accent: "green",
  },
  {
    start: 245.86,
    end: 251.6,
    eyebrow: "New-user workflow · 3",
    title: "Find confidence on desktop and mobile",
    platform: "Both platforms",
    layout: "dual",
    asset: "desktop-detail.png",
    sourceWidth: 1920,
    sourceHeight: 1080,
    crop: {x: 760, y: 295, width: 530, height: 420},
    mobileAsset: "mobile-detail.png",
    mobileSourceWidth: 1320,
    mobileSourceHeight: 2868,
    mobileCrop: {x: 640, y: 180, width: 680, height: 950},
    zoom: 1.16,
    mobileZoom: 1.14,
    callout: "Same score. Two convenient locations.",
    accent: "green",
  },
  {
    start: 251.6,
    end: 261.36,
    eyebrow: "New-user workflow · 4",
    title: "Inspect the reasons and contributing agents",
    platform: "Desktop + mobile",
    layout: "dual",
    asset: "desktop-agents.png",
    sourceWidth: 1920,
    sourceHeight: 1080,
    crop: {x: 390, y: 470, width: 930, height: 540},
    zoom: 1.15,
    mobileAsset: "mobile-model.png",
    mobileSourceWidth: 1320,
    mobileSourceHeight: 2868,
    mobileCrop: {x: 0, y: 850, width: 1320, height: 1950},
    mobileZoom: 1.13,
    callout: "Look for the factors doing the work.",
  },
  {
    start: 261.36,
    end: 273.22,
    eyebrow: "New-user workflow · 5",
    title: "Verify the current line and context",
    platform: "Mobile Line Check",
    layout: "mobile",
    asset: "mobile-detail.png",
    sourceWidth: 1320,
    sourceHeight: 2868,
    crop: {x: 0, y: 500, width: 1320, height: 1150},
    callout: "A moved line creates a different question.",
    accent: "green",
  },
  {
    start: 273.22,
    end: 282.6,
    eyebrow: "The practical decision",
    title: "Research further—or skip",
    platform: "No forced picks",
    layout: "dual",
    asset: "desktop-board.png",
    sourceWidth: 1920,
    sourceHeight: 1080,
    crop: {x: 205, y: 70, width: 1530, height: 890},
    mobileAsset: "mobile-picks.png",
    mobileSourceWidth: 1320,
    mobileSourceHeight: 2868,
    mobileCrop: {x: 0, y: 700, width: 1320, height: 1800},
    callout: "Skipping is always a valid outcome.",
    accent: "green",
  },
  {
    start: 282.6,
    end: 303.16,
    eyebrow: "The definition",
    title: "72 = a comparatively strong directional signal",
    platform: "Not a probability",
    layout: "dual",
    asset: "desktop-detail.png",
    sourceWidth: 1920,
    sourceHeight: 1080,
    crop: {x: 390, y: 120, width: 1320, height: 760},
    mobileAsset: "mobile-detail.png",
    mobileSourceWidth: 1320,
    mobileSourceHeight: 2868,
    mobileCrop: {x: 0, y: 185, width: 1320, height: 1750},
    callout: "Read confidence with direction, line, and evidence.",
  },
  {
    start: 303.16,
    end: 314.8,
    eyebrow: "One analysis system",
    title: "Deep research on desktop. Quick access on mobile.",
    platform: "Propeller Picks",
    layout: "dual",
    asset: "desktop-board.png",
    sourceWidth: 1920,
    sourceHeight: 1080,
    crop: {x: 205, y: 70, width: 1530, height: 890},
    mobileAsset: "mobile-detail.png",
    mobileSourceWidth: 1320,
    mobileSourceHeight: 2868,
    mobileCrop: {x: 0, y: 180, width: 1320, height: 1880},
    callout: "PropellerPicks.com",
    accent: "green",
  },
  {
    start: 314.8,
    end: 332.556,
    eyebrow: "Responsible use",
    title: "Research and analysis—not a sportsbook",
    platform: "Informational only",
    layout: "statement",
    callout: "1-800-GAMBLER",
    points: ["21+ where applicable", "No wagers accepted", "Informational research only"],
  },
];

export const DURATION_SECONDS = 332.556;
export const FPS = 30;
export const DURATION_IN_FRAMES = Math.ceil(DURATION_SECONDS * FPS);
