export type Crop = {x: number; y: number; width: number; height: number};
export type FocusRect = {x: number; y: number; width: number; height: number};

export type Card = {
  label: string;
  detail: string;
  value?: string;
};

export type Scene = {
  start: number;
  end: number;
  layout: "editorial" | "desktop" | "mobile" | "dual" | "signals" | "example" | "chart" | "workflow";
  eyebrow: string;
  title: string;
  callout?: string;
  signal?: number;
  asset?: string;
  crop?: Crop;
  focus?: FocusRect;
  mobileAsset?: string;
  mobileCrop?: Crop;
  mobileFocus?: FocusRect;
  cards?: Card[];
  points?: string[];
  historical?: boolean;
  accent?: "orange" | "green";
};

export const scenes: Scene[] = [
  {
    start: 0,
    end: 6.5,
    layout: "dual",
    eyebrow: "The common shortcut",
    title: "One screenshot is not an analysis",
    asset: "desktop-detail.png",
    crop: {x: 420, y: 480, width: 900, height: 440},
    mobileAsset: "mobile-detail.png",
    mobileCrop: {x: 0, y: 650, width: 1320, height: 2200},
    callout: "LAST 5 ≠ TONIGHT",
    historical: true,
  },
  {
    start: 6.5,
    end: 21.7,
    layout: "desktop",
    eyebrow: "Pull back",
    title: "The line lives inside a larger context",
    asset: "desktop-detail.png",
    crop: {x: 390, y: 100, width: 1320, height: 820},
    points: ["Role can change", "Teammates can return", "The market can move"],
    historical: true,
  },
  {
    start: 21.7,
    end: 31.5,
    layout: "signals",
    eyebrow: "The complete check",
    title: "Six connected signals",
    cards: [
      {label: "01", detail: "Volume"},
      {label: "02", detail: "Matchup"},
      {label: "03", detail: "Injuries"},
      {label: "04", detail: "Environment"},
      {label: "05", detail: "Recent form"},
      {label: "06", detail: "Market pricing"},
    ],
  },
  {
    start: 31.5,
    end: 43.3,
    layout: "editorial",
    eyebrow: "Before the trends",
    title: "Define the exact question",
    cards: [
      {label: "PLAYER", detail: "Who?"},
      {label: "STAT", detail: "Which category?"},
      {label: "DIRECTION", detail: "More or less?"},
      {label: "LINE", detail: "What exact number?"},
    ],
  },
  {
    start: 43.3,
    end: 49,
    layout: "example",
    eyebrow: "Illustrative question",
    title: "Will this player go over 24.5 points?",
    callout: "Specific. Testable. Line-aware.",
  },
  {
    start: 49,
    end: 62,
    layout: "editorial",
    eyebrow: "The half point matters",
    title: "Every signal answers to the line",
    cards: [
      {label: "POINTS", detail: "24.5", value: "OVER"},
      {label: "ASSISTS", detail: "6.5", value: "A different question"},
      {label: "PRA", detail: "39.5", value: "A different path"},
    ],
  },
  {
    start: 62,
    end: 69.9,
    layout: "editorial",
    eyebrow: "Signal 01",
    title: "Volume comes first",
    signal: 1,
    callout: "How many chances will the player have?",
  },
  {
    start: 69.9,
    end: 91,
    layout: "editorial",
    eyebrow: "Opportunity changes by sport",
    title: "Measure the role behind the result",
    signal: 1,
    cards: [
      {label: "BASKETBALL", detail: "Minutes · usage · potential assists"},
      {label: "FOOTBALL", detail: "Routes · targets · carries"},
      {label: "BASEBALL", detail: "Plate appearances · batters faced"},
      {label: "HOCKEY", detail: "Ice time · line · power play"},
    ],
  },
  {
    start: 91,
    end: 107,
    layout: "dual",
    eyebrow: "Volume inside Propeller",
    title: "Find the opportunity signal",
    signal: 1,
    asset: "desktop-agents.png",
    crop: {x: 370, y: 560, width: 1010, height: 430},
    focus: {x: 435, y: 842, width: 840, height: 52},
    mobileAsset: "mobile-model.png",
    mobileCrop: {x: 0, y: 650, width: 1320, height: 2200},
    mobileFocus: {x: 55, y: 2535, width: 1210, height: 285},
    callout: "Usage / Player Workload",
    historical: true,
  },
  {
    start: 107,
    end: 124,
    layout: "desktop",
    eyebrow: "Signal 02 · Matchup",
    title: "Evaluate this stat—not one overall rank",
    signal: 2,
    asset: "desktop-agents.png",
    crop: {x: 370, y: 560, width: 1010, height: 430},
    focus: {x: 435, y: 752, width: 840, height: 54},
    points: ["Scoring can differ from assists", "Rushing can differ from receiving", "Pitch mix can change the path"],
    historical: true,
  },
  {
    start: 124,
    end: 143.4,
    layout: "editorial",
    eyebrow: "Matchup must be specific",
    title: "Player × stat × opponent",
    signal: 2,
    cards: [
      {label: "BASKETBALL", detail: "Scoring defense can hide assist allowance"},
      {label: "FOOTBALL", detail: "Rushing and receiving paths diverge"},
      {label: "BASEBALL", detail: "Handedness · pitch mix · lineup slot"},
    ],
    callout: "Ask how the exact path is affected.",
  },
  {
    start: 143.4,
    end: 162,
    layout: "dual",
    eyebrow: "Signal 03 · Injuries",
    title: "One status can reshape the whole lineup",
    signal: 3,
    asset: "desktop-agents.png",
    crop: {x: 370, y: 560, width: 1010, height: 430},
    focus: {x: 435, y: 708, width: 840, height: 54},
    mobileAsset: "mobile-model.png",
    mobileCrop: {x: 0, y: 650, width: 1320, height: 2200},
    mobileFocus: {x: 80, y: 1550, width: 1140, height: 380},
    callout: "Direct status + cascade effects",
    historical: true,
  },
  {
    start: 162,
    end: 176,
    layout: "workflow",
    eyebrow: "Injury workflow",
    title: "Check the chain—then check again",
    signal: 3,
    points: ["Player status", "Key teammates", "Relevant opponents", "Recheck near game time"],
  },
  {
    start: 176,
    end: 197,
    layout: "editorial",
    eyebrow: "Signal 04 · Environment",
    title: "The setting changes the opportunity",
    signal: 4,
    cards: [
      {label: "PACE", detail: "Possessions and tempo"},
      {label: "SCRIPT", detail: "How the game may unfold"},
      {label: "CONDITIONS", detail: "Weather and venue"},
      {label: "REST", detail: "Travel and workload"},
    ],
  },
  {
    start: 197,
    end: 221,
    layout: "desktop",
    eyebrow: "Environment inside Propeller",
    title: "Use the factors available for this sport",
    signal: 4,
    asset: "desktop-agents.png",
    crop: {x: 370, y: 560, width: 1010, height: 430},
    focus: {x: 435, y: 798, width: 840, height: 54},
    points: ["Ballpark for this MLB example", "Other sports expose different context", "No one factor decides the prop"],
    historical: true,
  },
  {
    start: 221,
    end: 239.5,
    layout: "dual",
    eyebrow: "Signal 05 · Recent form",
    title: "Useful context. Easy to misuse.",
    signal: 5,
    asset: "desktop-detail.png",
    crop: {x: 420, y: 480, width: 900, height: 440},
    mobileAsset: "mobile-detail.png",
    mobileCrop: {x: 0, y: 550, width: 1320, height: 2200},
    callout: "7 of 10 is not a 70% forecast",
    historical: true,
  },
  {
    start: 239.5,
    end: 264.6,
    layout: "chart",
    eyebrow: "Compare like with like",
    title: "Past result vs. tonight’s exact line",
    signal: 5,
    callout: "22 points does not clear 24.5",
    points: ["Did minutes increase?", "Did usage change?", "Was conversion unusually high?"],
  },
  {
    start: 264.6,
    end: 283,
    layout: "desktop",
    eyebrow: "Signal 06 · Market pricing",
    title: "Remove the margin to reveal the baseline",
    signal: 6,
    asset: "desktop-detail.png",
    crop: {x: 770, y: 420, width: 950, height: 480},
    focus: {x: 1305, y: 520, width: 390, height: 385},
    callout: "Implied probability → no-vig probability",
    historical: true,
  },
  {
    start: 283,
    end: 306.3,
    layout: "dual",
    eyebrow: "Read the line in context",
    title: "Market agreement—and disagreement—matters",
    signal: 6,
    asset: "desktop-detail.png",
    crop: {x: 770, y: 420, width: 950, height: 480},
    mobileAsset: "mobile-detail.png",
    mobileCrop: {x: 0, y: 350, width: 1320, height: 2200},
    mobileFocus: {x: 70, y: 760, width: 1180, height: 680},
    callout: "Sportsbooks and pick’em platforms price differently",
    historical: true,
  },
  {
    start: 306.3,
    end: 318.6,
    layout: "signals",
    eyebrow: "Do not tally votes",
    title: "The six signals are not equally important",
    cards: [
      {label: "ROLE", detail: "Can dominate basketball"},
      {label: "MATCHUP", detail: "Can dominate baseball"},
      {label: "NEWS", detail: "Can override an older trend"},
    ],
  },
  {
    start: 318.6,
    end: 330.3,
    layout: "desktop",
    eyebrow: "Agent breakdown",
    title: "See agreement, conflict, and the reason why",
    asset: "desktop-agents.png",
    crop: {x: 370, y: 560, width: 1010, height: 430},
    callout: "Sport-specific contributors",
    historical: true,
  },
  {
    start: 330.3,
    end: 346,
    layout: "dual",
    eyebrow: "Confidence in context",
    title: "A directional research signal—not a guarantee",
    asset: "desktop-detail.png",
    crop: {x: 745, y: 280, width: 570, height: 300},
    focus: {x: 860, y: 365, width: 210, height: 145},
    mobileAsset: "mobile-detail.png",
    mobileCrop: {x: 600, y: 190, width: 700, height: 1160},
    mobileFocus: {x: 865, y: 345, width: 330, height: 330},
    callout: "Confidence ≠ exact chance to hit",
    historical: true,
  },
  {
    start: 346,
    end: 365,
    layout: "workflow",
    eyebrow: "Repeatable workflow · 1–3",
    title: "Define. Evaluate. Diagnose.",
    points: ["Confirm player, stat, direction, line", "Evaluate all six signals", "Find the main driver and disagreement"],
  },
  {
    start: 365,
    end: 389,
    layout: "dual",
    eyebrow: "Repeatable workflow · 4–5",
    title: "Verify the current context—then choose",
    asset: "desktop-board.png",
    crop: {x: 205, y: 70, width: 1530, height: 890},
    mobileAsset: "mobile-picks.png",
    mobileCrop: {x: 20, y: 180, width: 1280, height: 1680},
    callout: "RESEARCH FURTHER  /  SKIP",
    historical: true,
  },
  {
    start: 389,
    end: 403,
    layout: "editorial",
    eyebrow: "Propeller Picks",
    title: "Research the line. Understand the signal.",
    callout: "PropellerPicks.com",
    cards: [
      {label: "EXPLORE", detail: "Prop Analyzer"},
      {label: "USE IT YOUR WAY", detail: "Desktop + mobile"},
      {label: "NEXT", detail: "Subscribe for more"},
    ],
    accent: "green",
  },
  {
    start: 403,
    end: 413,
    layout: "editorial",
    eyebrow: "Research and analytics",
    title: "No guarantees. No sportsbook. Just a clearer process.",
    callout: "If you choose to wager, be responsible and follow local laws.",
  },
];

export const FPS = 30;
export const DURATION_SECONDS = 413;
export const DURATION_IN_FRAMES = FPS * DURATION_SECONDS;
