import {Audio} from "@remotion/media";
import React from "react";
import {AbsoluteFill, Easing, Img, interpolate, Sequence, staticFile, useCurrentFrame} from "remotion";
import {Captions} from "./Captions";
import {agents, fixture, FPS, mobileAgentNames, scenes} from "./data";
import "./fonts";

const C = {ink: "#101522", slate: "#4d5768", paper: "#f4f5f7", white: "#ffffff", orange: "#f87552", green: "#16825a", blue: "#4666e5", red: "#de4c4c"};
const clamp = {extrapolateLeft: "clamp" as const, extrapolateRight: "clamp" as const};

const PropellerMark: React.FC<{size?: number; color?: string}> = ({size = 40, color = C.orange}) => <svg width={size} height={size} viewBox="0 0 54 54"><circle cx="27" cy="27" r="5.5" fill={color}/><path d="M27 27V5M27 27L7 40M27 27L47 40" stroke={color} strokeWidth="7.5" strokeLinecap="round"/></svg>;
const Pill: React.FC<{children: React.ReactNode; tone?: "orange"|"green"|"dark"|"light"}> = ({children, tone="light"}) => {
  const map = {orange:["#fff0ea",C.orange],green:["#eaf8f2",C.green],dark:[C.ink,C.white],light:[C.white,C.slate]} as const;
  return <span style={{display:"inline-flex",alignItems:"center",padding:"8px 13px",borderRadius:999,background:map[tone][0],color:map[tone][1],fontFamily:"IBM Plex Mono",fontSize:13,fontWeight:600,letterSpacing:.7,border:`1px solid ${tone==="light"?"#dfe3e9":map[tone][0]}`}}>{children}</span>;
};

const BrandHeader: React.FC<{historical?: boolean}> = ({historical}) => <div style={{height:64,flexShrink:0,display:"flex",alignItems:"center",justifyContent:"space-between"}}>
  <div style={{display:"flex",alignItems:"center",gap:12}}><PropellerMark/><div><div style={{fontFamily:"Familjen Grotesk",fontSize:25,fontWeight:700,lineHeight:.9}}>PROPELLER</div><div style={{fontFamily:"IBM Plex Mono",fontSize:10,letterSpacing:5,color:C.orange,marginTop:6}}>PICKS</div></div></div>
  {historical?<Pill tone="green">HISTORICAL WORKFLOW EXAMPLE · NOT A LIVE PICK</Pill>:<Pill>PLAYER PROP RESEARCH</Pill>}
</div>;

const Grid: React.FC = () => <AbsoluteFill style={{background:C.paper,backgroundImage:"linear-gradient(rgba(16,21,34,.045) 1px,transparent 1px),linear-gradient(90deg,rgba(16,21,34,.045) 1px,transparent 1px)",backgroundSize:"36px 36px"}}/>;

const SceneShell: React.FC<{eyebrow:string;title:string;historical?:boolean;children:React.ReactNode}> = ({eyebrow,title,historical,children}) => {
  const f=useCurrentFrame(); const opacity=interpolate(f,[0,10],[0,1],clamp); const y=interpolate(f,[0,13],[18,0],{...clamp,easing:Easing.out(Easing.cubic)});
  return <AbsoluteFill style={{overflow:"hidden",color:C.ink}}><Grid/><div style={{position:"relative",height:"100%",padding:"32px 66px 112px",display:"flex",flexDirection:"column",gap:14}}><BrandHeader historical={historical}/><div style={{opacity,transform:`translateY(${y}px)`,flexShrink:0}}><div style={{fontFamily:"IBM Plex Mono",fontSize:16,letterSpacing:2.4,color:C.orange,fontWeight:600}}>{eyebrow}</div><div style={{fontFamily:"Familjen Grotesk",fontSize:60,fontWeight:700,letterSpacing:-1.9,lineHeight:1,marginTop:7}}>{title}</div></div><div style={{flex:1,minHeight:0}}>{children}</div></div></AbsoluteFill>;
};

const BrowserFrame: React.FC<{children:React.ReactNode; width?:number;height?:number}> = ({children,width=1180,height=570}) => <div style={{width,height,borderRadius:15,background:C.ink,padding:"42px 9px 9px",position:"relative",boxShadow:"14px 16px 0 rgba(248,117,82,.18)",overflow:"hidden"}}><div style={{position:"absolute",top:15,left:18,display:"flex",gap:8}}>{[C.orange,"#ffd06b",C.green].map(x=><i key={x} style={{width:11,height:11,borderRadius:99,background:x}}/>)}</div><div style={{position:"absolute",top:10,left:118,right:16,height:24,borderRadius:5,background:"#283041",color:"#c8cfda",fontFamily:"IBM Plex Mono",fontSize:11,padding:"5px 12px"}}>app.propellerpicks.com</div><div style={{height:"100%",background:"#f7f8fa",borderRadius:8,overflow:"hidden"}}>{children}</div></div>;
const PhoneFrame: React.FC<{children:React.ReactNode;width?:number;height?:number}> = ({children,width=350,height=610}) => <div style={{width,height,borderRadius:48,background:C.ink,padding:12,border:"4px solid #3a4354",boxShadow:"12px 14px 0 rgba(70,102,229,.14)",position:"relative"}}><div style={{position:"absolute",zIndex:3,top:18,left:"50%",transform:"translateX(-50%)",width:88,height:20,borderRadius:20,background:C.ink}}/><div style={{height:"100%",borderRadius:34,overflow:"hidden",background:"#f6f8fb"}}>{children}</div></div>;

const ConfidenceRing: React.FC<{size?:number}> = ({size=112}) => <div style={{width:size,height:size,borderRadius:"50%",background:`conic-gradient(${C.orange} 0 62%,#e5e8ee 62% 100%)`,padding:8,display:"grid",placeItems:"center"}}><div style={{width:"100%",height:"100%",borderRadius:"50%",background:C.white,display:"grid",placeItems:"center",fontFamily:"Familjen Grotesk",fontSize:size*.34,fontWeight:700,color:C.ink}}>{fixture.confidence}<span style={{fontFamily:"IBM Plex Mono",fontSize:size*.095,color:C.slate,marginTop:-size*.25}}>CONF</span></div></div>;

const DesktopProp: React.FC<{focus?:"identity"|"direction"|"confidence"|"agents"|"matchup"|"injury"|"disagreement"}> = ({focus}) => {
  const focusStyle=(key:string)=>focus===key?{outline:`4px solid ${C.orange}`,boxShadow:"0 0 0 8px rgba(248,117,82,.14)"}:{};
  return <div style={{height:"100%",padding:"28px 34px",fontFamily:"IBM Plex Sans",color:C.ink,overflow:"hidden"}}>
    <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",borderBottom:"1px solid #e4e7ec",paddingBottom:18}}><div style={{display:"flex",alignItems:"center",gap:12}}><PropellerMark size={28}/><b style={{fontFamily:"Familjen Grotesk",fontSize:22}}>Propeller</b></div><div style={{display:"flex",gap:25,fontSize:13,color:C.slate}}><b>NFL BOARD</b><span>ANALYZER</span><span>RESULTS</span></div></div>
    <div style={{display:"grid",gridTemplateColumns:"1.22fr .78fr",gap:24,marginTop:22}}>
      <div>
        <div style={{border:"1px solid #e1e5eb",borderRadius:15,background:C.white,padding:22,...focusStyle("identity")}}>
          <div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start"}}><div><div style={{fontFamily:"IBM Plex Mono",fontSize:11,letterSpacing:1.2,color:C.slate}}>{fixture.week} · {fixture.date}</div><div style={{fontFamily:"Familjen Grotesk",fontSize:37,fontWeight:700,marginTop:7}}>{fixture.player}</div><div style={{color:C.slate,fontSize:15}}>Buffalo · Quarterback</div></div><ConfidenceRing/></div>
          <div style={{display:"grid",gridTemplateColumns:"1.2fr .7fr .8fr",gap:12,marginTop:18}}><DataCell label="STAT" value={fixture.stat}/><DataCell label="LINE" value={fixture.line}/><DataCell label="PLATFORM" value={fixture.platform}/></div>
          <div style={{display:"flex",gap:12,marginTop:14}}><div style={{flex:1,border:`2px solid ${C.orange}`,borderRadius:11,padding:"14px 17px",background:"#fff2ed",...focusStyle("direction")}}><small style={{fontFamily:"IBM Plex Mono",color:C.slate}}>DISPLAY DIRECTION</small><div style={{fontFamily:"Familjen Grotesk",fontSize:31,fontWeight:700,color:C.orange}}>{fixture.direction} {fixture.line}</div></div><div style={{width:150,border:"1px solid #e4e7ec",borderRadius:11,padding:13,display:"grid",placeItems:"center",...focusStyle("confidence")}}><div style={{fontFamily:"IBM Plex Mono",fontSize:12,color:C.slate}}>CONFIDENCE</div><b style={{fontFamily:"Familjen Grotesk",fontSize:34}}>{fixture.confidence}</b></div></div>
        </div>
        <div style={{marginTop:15,background:"#eef7f3",border:"1px solid #cfe7dc",borderRadius:11,padding:"11px 14px",fontFamily:"IBM Plex Mono",fontSize:11,color:C.green}}>HISTORICAL WORKFLOW EXAMPLE — NOT A LIVE OR PUBLISHED PREGAME RECOMMENDATION</div>
      </div>
      <div style={{border:"1px solid #e1e5eb",borderRadius:15,background:C.white,padding:18,...focusStyle(focus==="injury"?"injury":focus==="matchup"?"matchup":focus==="disagreement"?"disagreement":"agents")}}><div style={{fontFamily:"Familjen Grotesk",fontSize:25,fontWeight:700}}>Agent breakdown</div><div style={{fontSize:12,color:C.slate,marginTop:3}}>Saved signals from the archived record</div><div style={{display:"grid",gap:7,marginTop:13}}>{agents.map(a=><AgentRow key={a.name} agent={a} emphasized={(focus==="injury"&&a.name==="Injury")||(focus==="matchup"&&a.name==="Matchup")||(focus==="disagreement"&&["Matchup","Volume"].includes(a.name))}/>)}</div></div>
    </div>
  </div>;
};
const DataCell:React.FC<{label:string;value:string}> = ({label,value})=><div style={{background:"#f4f6f9",borderRadius:9,padding:"11px 13px"}}><div style={{fontFamily:"IBM Plex Mono",fontSize:10,color:C.slate}}>{label}</div><b style={{fontFamily:"Familjen Grotesk",fontSize:value.length>12?17:24}}>{value}</b></div>;
const AgentRow:React.FC<{agent:typeof agents[number];emphasized?:boolean;compact?:boolean}>=({agent,emphasized,compact})=>{const width=Math.max(5,Math.min(100,agent.score));return <div style={{padding:compact?"6px 8px":"7px 9px",borderRadius:8,background:emphasized?"#fff0ea":"#f6f7f9",border:emphasized?`2px solid ${C.orange}`:"1px solid transparent"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",fontSize:compact?10:11}}><span style={{fontWeight:600}}>{agent.label}</span><b style={{fontFamily:"IBM Plex Mono",color:agent.score>=50?C.green:C.orange}}>{Math.round(agent.score)}</b></div><div style={{height:5,borderRadius:9,background:"#e1e5ea",marginTop:5,overflow:"hidden"}}><div style={{width:`${width}%`,height:"100%",background:agent.score>=50?C.green:C.orange}}/></div></div>};

const MobileProp:React.FC<{focus?:"identity"|"direction"|"confidence"|"agents"}> = ({focus}) => <div style={{height:"100%",padding:"44px 14px 16px",fontFamily:"IBM Plex Sans",color:C.ink,overflow:"hidden"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><div style={{display:"flex",alignItems:"center",gap:7}}><PropellerMark size={22}/><b style={{fontFamily:"Familjen Grotesk"}}>Propeller</b></div><span style={{fontSize:17}}>•••</span></div><div style={{marginTop:18,border:"1px solid #e1e5eb",borderRadius:14,background:C.white,padding:14,outline:focus==="identity"?`3px solid ${C.orange}`:"none"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><div><div style={{fontFamily:"IBM Plex Mono",fontSize:8,color:C.slate}}>{fixture.week}</div><div style={{fontFamily:"Familjen Grotesk",fontSize:25,fontWeight:700}}>{fixture.player}</div><div style={{fontSize:11,color:C.slate}}>Buffalo · QB</div></div><div style={{borderRadius:99,outline:focus==="confidence"?`4px solid ${C.orange}`:"none",outlineOffset:4}}><ConfidenceRing size={76}/></div></div><div style={{fontFamily:"IBM Plex Mono",fontSize:9,color:C.slate,marginTop:12}}>PASSING YARDS · LINE {fixture.line}</div><div style={{borderRadius:9,padding:"10px 12px",background:"#fff1ec",marginTop:7,outline:focus==="direction"?`3px solid ${C.orange}`:"none"}}><div style={{fontSize:9,color:C.slate}}>DISPLAY DIRECTION</div><div style={{fontFamily:"Familjen Grotesk",fontSize:24,fontWeight:700,color:C.orange}}>{fixture.direction} {fixture.line}</div></div></div><div style={{marginTop:10,border:"1px solid #e1e5eb",borderRadius:14,background:C.white,padding:12,outline:focus==="agents"?`3px solid ${C.orange}`:"none"}}><div style={{fontFamily:"Familjen Grotesk",fontSize:19,fontWeight:700}}>Agent breakdown</div><div style={{display:"grid",gap:5,marginTop:8}}>{agents.filter(a=>mobileAgentNames.has(a.name)).map(a=><AgentRow key={a.name} agent={a} compact/>)}</div></div><div style={{marginTop:9,fontFamily:"IBM Plex Mono",fontSize:8,lineHeight:1.35,color:C.green}}>HISTORICAL EXAMPLE · NOT A LIVE PICK</div></div>;

const CurrentBoard:React.FC = () => <div style={{display:"grid",gridTemplateColumns:"1.5fr .55fr",gap:42,alignItems:"center",height:"100%"}}><BrowserFrame><Img src={staticFile("captures/current-nfl-desktop.png")} style={{width:"100%",height:"100%",objectFit:"cover",objectPosition:"center 62%"}}/></BrowserFrame><PhoneFrame><div style={{height:"100%",padding:"46px 17px 20px",fontFamily:"IBM Plex Sans",textAlign:"center"}}><div style={{display:"flex",alignItems:"center",gap:8,textAlign:"left"}}><PropellerMark size={22}/><b style={{fontFamily:"Familjen Grotesk"}}>Propeller</b></div><div style={{marginTop:43,fontFamily:"IBM Plex Mono",color:C.orange,fontSize:10}}>NFL PLAYER PROP RESEARCH</div><div style={{fontFamily:"Familjen Grotesk",fontSize:27,fontWeight:700,lineHeight:1.02,marginTop:8}}>Verified Slate Status</div><div style={{marginTop:48,border:"1px solid #dfe3e9",borderRadius:14,background:C.white,padding:"28px 14px"}}><div style={{fontSize:32}}>▣</div><div style={{fontFamily:"Familjen Grotesk",fontSize:22,fontWeight:700}}>NFL off-season</div><p style={{fontSize:12,lineHeight:1.45,color:C.slate}}>NFL regular-season props return when the season opens.</p><Pill tone="orange">0 CURRENT PROPS</Pill></div><div style={{fontFamily:"IBM Plex Mono",fontSize:9,color:C.slate,marginTop:18}}>CHECKED · JUL 29, 2026</div></div></PhoneFrame></div>;

const DualProp:React.FC<{focus?:"identity"|"direction"|"confidence"|"agents"}> = ({focus}) => <div style={{display:"grid",gridTemplateColumns:"1.48fr .47fr",gap:38,alignItems:"center",height:"100%"}}><BrowserFrame><DesktopProp focus={focus}/></BrowserFrame><PhoneFrame><MobileProp focus={focus}/></PhoneFrame></div>;

const DisclosureScene:React.FC = () => <div style={{height:"100%",position:"relative"}}><DualProp focus="identity"/><div style={{position:"absolute",left:80,top:185,width:760,background:"rgba(16,21,34,.96)",color:C.white,borderRadius:15,padding:"30px 34px",boxShadow:`12px 14px 0 ${C.orange}`}}><div style={{fontFamily:"IBM Plex Mono",fontSize:15,color:C.orange}}>JOSH ALLEN · 2025 WEEK 17</div><div style={{fontFamily:"Familjen Grotesk",fontSize:41,fontWeight:700,lineHeight:1.05,marginTop:14}}>Interface demonstration only.</div><div style={{fontFamily:"IBM Plex Sans",fontSize:20,lineHeight:1.4,color:"#d6dbe4",marginTop:13}}>Not live. Not published pregame. Not actionable.</div></div></div>;

const DirectionScene:React.FC = () => {const f=useCurrentFrame(); return <DualProp focus={f < 370 ? "direction" : "confidence"}/>;};

const QuestionCards:React.FC<{items:string[];tone?:string}> = ({items,tone=C.orange}) => <div style={{display:"grid",gridTemplateColumns:"repeat(2,1fr)",gap:14}}>{items.map((x,i)=><div key={x} style={{background:i===0?"#fff0ea":C.white,border:"1px solid #dde2e8",borderLeft:`7px solid ${tone}`,borderRadius:10,padding:"18px 20px",fontFamily:"Familjen Grotesk",fontSize:26,fontWeight:700,lineHeight:1.08}}>{x}</div>)}</div>;

const RoleScene:React.FC = () => <div style={{display:"grid",gridTemplateColumns:"1.35fr .65fr",gap:38,alignItems:"center",height:"100%"}}><BrowserFrame width={1100}><DesktopProp focus="identity"/></BrowserFrame><div><QuestionCards items={["Attempts","Designed runs","Pass rate","Expected script"]}/><div style={{marginTop:18,padding:18,background:C.ink,color:C.white,borderRadius:10,fontFamily:"IBM Plex Sans",fontSize:21,lineHeight:1.35}}>Is the role that created the opportunity still present this week?</div></div></div>;
const InjuryScene:React.FC = () => <div style={{display:"grid",gridTemplateColumns:".78fr 1.22fr",gap:36,alignItems:"center",height:"100%"}}><div style={{background:C.white,border:"1px solid #dfe3e9",borderRadius:15,padding:28,boxShadow:"12px 12px 0 rgba(70,102,229,.12)"}}><Pill tone="dark">PRIMARY SOURCE</Pill><div style={{fontFamily:"Familjen Grotesk",fontSize:38,fontWeight:700,marginTop:20}}>Official NFL injury report</div><div style={{display:"grid",gap:10,marginTop:22}}>{["Practice status","Game designation","Inactive list","Teammate effects"].map((x,i)=><div key={x} style={{display:"flex",alignItems:"center",gap:13,padding:13,borderRadius:8,background:i===3?"#fff0ea":"#f5f7fa",fontFamily:"IBM Plex Sans",fontSize:20,fontWeight:600}}><span style={{color:i===3?C.orange:C.green}}>✓</span>{x}</div>)}</div><div style={{fontFamily:"IBM Plex Mono",fontSize:12,color:C.slate,marginTop:19}}>VERIFY AGAIN AS KICKOFF APPROACHES</div></div><BrowserFrame width={1060}><DesktopProp focus="injury"/></BrowserFrame></div>;
const MatchupScene:React.FC = () => <div style={{display:"grid",gridTemplateColumns:"1.35fr .65fr",gap:38,alignItems:"center",height:"100%"}}><BrowserFrame width={1100}><DesktopProp focus="matchup"/></BrowserFrame><QuestionCards tone={C.blue} items={["Position-specific defense","Pace + pass/run environment","Outdoor weather","Possible game scripts"]}/></div>;
const AgentsScene:React.FC<{disagreement?:boolean}> = ({disagreement}) => <div style={{display:"grid",gridTemplateColumns:"1.5fr .45fr",gap:38,alignItems:"center",height:"100%"}}><BrowserFrame><DesktopProp focus={disagreement?"disagreement":"agents"}/></BrowserFrame><PhoneFrame><MobileProp focus="agents"/></PhoneFrame></div>;

const FourFields:React.FC = () => <div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:18,alignItems:"stretch",height:"100%",paddingTop:70}}>{[
  ["DIRECTION","UNDER","Signals lean below the line"],["CONFIDENCE","62","Directional signal strength"],["LINE","195.5","The listed decision threshold"],["MARKET PROBABILITY","—","Requires retained listed prices"],
].map(([a,b,c],i)=><div key={a} style={{height:300,border:`2px solid ${i===1?C.orange:"#d9dee6"}`,borderRadius:15,background:C.white,padding:26,boxShadow:i===1?"10px 12px 0 rgba(248,117,82,.18)":"none"}}><div style={{fontFamily:"IBM Plex Mono",fontSize:14,color:i===1?C.orange:C.slate}}>{a}</div><div style={{fontFamily:"Familjen Grotesk",fontSize:56,fontWeight:700,marginTop:27}}>{b}</div><div style={{fontFamily:"IBM Plex Sans",fontSize:18,lineHeight:1.3,color:C.slate,marginTop:20}}>{c}</div></div>)}</div>;
const Movement:React.FC = () => <div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:22,alignItems:"center",height:"100%"}}>{[["01","CHANGED LINE","The market changed."],["02","NEW QUESTION","Why did it change?"],["03","VERIFY AGAIN","Current line + timestamp"]].map(([n,t,d],i)=><React.Fragment key={n}><div style={{border:`2px solid ${i===1?C.orange:"#d8dde5"}`,borderRadius:15,background:i===1?"#fff0ea":C.white,padding:30,minHeight:250}}><div style={{fontFamily:"IBM Plex Mono",color:C.orange,fontSize:16}}>{n}</div><div style={{fontFamily:"Familjen Grotesk",fontSize:38,fontWeight:700,marginTop:33}}>{t}</div><div style={{fontFamily:"IBM Plex Sans",fontSize:20,color:C.slate,marginTop:13}}>{d}</div></div>{i<2?<div style={{position:"absolute",display:"none"}}>→</div>:null}</React.Fragment>)}</div>;
const Checklist:React.FC = () => {const f=useCurrentFrame(); const items=["Current slate","Exact player · stat · line · platform","Expected role intact","Official injuries + inactives current","Matchup + environment assumptions","Agent disagreement understood","Clear reason to pass"]; return <div style={{display:"grid",gridTemplateColumns:"1.2fr .8fr",gap:38,alignItems:"center",height:"100%"}}><BrowserFrame width={1050}><DesktopProp focus="identity"/></BrowserFrame><div style={{display:"grid",gap:10}}>{items.map((x,i)=><div key={x} style={{opacity:interpolate(f,[i*11,i*11+9],[0,1],clamp),transform:`translateX(${interpolate(f,[i*11,i*11+9],[18,0],clamp)}px)`,background:C.white,border:"1px solid #dfe3e9",borderRadius:9,padding:"13px 16px",fontFamily:"IBM Plex Sans",fontSize:19,fontWeight:600}}><span style={{color:i===6?C.orange:C.green,marginRight:12}}>{i===6?"?":"✓"}</span>{x}</div>)}</div></div>};
const PassScene:React.FC = () => <div style={{height:"100%",display:"grid",placeItems:"center"}}><div style={{width:1320,borderRadius:18,background:C.ink,color:C.white,padding:"52px 62px",boxShadow:`16px 18px 0 ${C.orange}`}}><div style={{fontFamily:"IBM Plex Mono",fontSize:18,color:C.orange}}>MOVED LINE · UNCERTAIN ROLE · STALE EVIDENCE</div><div style={{fontFamily:"Familjen Grotesk",fontSize:92,fontWeight:700,lineHeight:.95,marginTop:22}}>Walking away is a valid conclusion.</div></div></div>;
const Freshness:React.FC = () => <div style={{height:"100%",display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:18,alignItems:"center"}}>{[["01","SLATE"],["02","LINE + TIME"],["03","OFFICIAL STATUS"],["04","DECIDE"]].map(([n,t],i)=><div key={n} style={{height:220,borderRadius:14,background:i===3?C.ink:C.white,color:i===3?C.white:C.ink,border:"1px solid #dfe3e9",padding:28}}><div style={{fontFamily:"IBM Plex Mono",fontSize:16,color:C.orange}}>{n}</div><div style={{fontFamily:"Familjen Grotesk",fontSize:37,fontWeight:700,marginTop:45}}>{t}</div></div>)}</div>;
const Intro:React.FC = () => <div style={{display:"grid",gridTemplateColumns:".68fr 1.32fr",gap:50,alignItems:"center",height:"100%"}}><div><div style={{fontFamily:"IBM Plex Sans",fontSize:27,lineHeight:1.4,color:C.slate}}>Verify the decision first. Then research the assumptions behind it.</div><div style={{display:"grid",gap:11,marginTop:26}}>{["Slate + exact line","Role + injuries","Matchup + environment","Agents + confidence"].map((x,i)=><div key={x} style={{display:"flex",alignItems:"center",gap:14,fontFamily:"Familjen Grotesk",fontSize:27,fontWeight:700}}><span style={{fontFamily:"IBM Plex Mono",fontSize:13,color:C.orange}}>0{i+1}</span>{x}</div>)}</div></div><DualProp focus="identity"/></div>;
const CTA:React.FC = () => <div style={{display:"grid",gridTemplateColumns:"1.1fr .9fr",gap:50,alignItems:"center",height:"100%"}}><div><div style={{fontFamily:"IBM Plex Sans",fontSize:27,lineHeight:1.45,color:C.slate}}>Save the NFL Player Prop Research Guide. Open the Analyzer when a verified slate is available.</div><div style={{display:"flex",gap:14,marginTop:28}}><Pill tone="orange">PROPELLERPICKS.COM/GUIDES</Pill><Pill tone="dark">OPEN THE ANALYZER</Pill></div><div style={{fontFamily:"IBM Plex Mono",fontSize:13,lineHeight:1.6,color:C.slate,marginTop:34}}>Independent research and analytics platform.<br/>No model signal guarantees an outcome.</div></div><div style={{borderRadius:18,background:C.ink,color:C.white,padding:46,boxShadow:`15px 17px 0 ${C.orange}`}}><PropellerMark size={66}/><div style={{fontFamily:"Familjen Grotesk",fontSize:70,fontWeight:700,lineHeight:.9,marginTop:24}}>Propeller</div><div style={{fontFamily:"IBM Plex Mono",letterSpacing:9,color:C.orange,marginTop:15}}>PICKS</div><div style={{height:2,background:"#343d50",margin:"32px 0"}}/><div style={{fontFamily:"IBM Plex Sans",fontSize:21,lineHeight:1.4,color:"#d7dce5"}}>Use limits. Treat research as one input in your own decision.</div></div></div>;

const Scene:React.FC<{scene:typeof scenes[number]}> = ({scene}) => {const historical=!(["intro","availability"].includes(scene.kind)); let body:React.ReactNode;
  switch(scene.kind){case"intro":body=<Intro/>;break;case"availability":body=<CurrentBoard/>;break;case"disclosure":body=<DisclosureScene/>;break;case"identity":body=<DualProp focus="identity"/>;break;case"role":body=<RoleScene/>;break;case"injury":body=<InjuryScene/>;break;case"matchup":body=<MatchupScene/>;break;case"agents":body=<AgentsScene/>;break;case"disagreement":body=<AgentsScene disagreement/>;break;case"direction":body=<DirectionScene/>;break;case"probability":body=<FourFields/>;break;case"movement":body=<Movement/>;break;case"checklist":body=<Checklist/>;break;case"pass":body=<PassScene/>;break;case"freshness":body=<Freshness/>;break;default:body=<CTA/>;}
  return <SceneShell eyebrow={scene.eyebrow} title={scene.title} historical={historical}>{body}</SceneShell>;
};

export const NFLPropWorkflow:React.FC<{showCaptions:boolean}> = ({showCaptions}) => <AbsoluteFill style={{background:C.paper}}><Audio src={staticFile("assets/narration.mp3")}/>{scenes.map(s=><Sequence key={`${s.start}-${s.kind}`} from={Math.round(s.start*FPS)} durationInFrames={Math.round((s.end-s.start)*FPS)}><Scene scene={s}/></Sequence>)}{showCaptions?<Captions/>:null}</AbsoluteFill>;
